// Generates content/jobs/*.json and content/locations/*.json from ONS ASHE 2023/24 data.
// Run: node scripts/generateSeedData.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const JOBS_DIR = join(ROOT, 'src/content/jobs');
const LOCS_DIR = join(ROOT, 'src/content/locations');
const COMP_DIR = join(ROOT, 'src/content/companies');
mkdirSync(JOBS_DIR, { recursive: true });
mkdirSync(LOCS_DIR, { recursive: true });
mkdirSync(COMP_DIR, { recursive: true });

const TODAY = new Date().toISOString().slice(0, 10);

// ONS ASHE 2023/24 median + quartile salary data (UK gross annual, full-time).
// Sources: ONS Annual Survey of Hours and Earnings 2023, ONS Occupation earnings tables.
const jobs = [
  // Technology
  { slug: 'software-engineer', title: 'Software Engineer', category: 'Technology', soc: '2136',
    median: 52000, lq: 38000, uq: 72000, min: 28000, max: 120000, entry: 32000, senior: 95000,
    alts: ['Software Developer', 'Programmer', 'Coder', 'Application Developer'],
    skills: ['JavaScript', 'Python', 'Git', 'SQL', 'System design', 'Agile'],
    related: ['devops-engineer', 'data-analyst', 'product-manager'],
    growth: 'high' },
  { slug: 'data-analyst', title: 'Data Analyst', category: 'Technology', soc: '2425',
    median: 38000, lq: 30000, uq: 50000, min: 24000, max: 75000, entry: 26000, senior: 65000,
    alts: ['Business Analyst', 'BI Analyst', 'Analytics Consultant'],
    skills: ['SQL', 'Excel', 'Power BI', 'Tableau', 'Python', 'Statistics'],
    related: ['software-engineer', 'financial-analyst', 'product-manager'],
    growth: 'high' },
  { slug: 'product-manager', title: 'Product Manager', category: 'Technology', soc: '2425',
    median: 65000, lq: 48000, uq: 88000, min: 35000, max: 140000, entry: 42000, senior: 115000,
    alts: ['Product Owner', 'Technical Product Manager', 'Senior PM'],
    skills: ['Roadmap planning', 'User research', 'Agile', 'Stakeholder management', 'Analytics'],
    related: ['software-engineer', 'ux-designer', 'marketing-manager'],
    growth: 'high' },
  { slug: 'devops-engineer', title: 'DevOps Engineer', category: 'Technology', soc: '2139',
    median: 58000, lq: 44000, uq: 78000, min: 32000, max: 120000, entry: 38000, senior: 105000,
    alts: ['Site Reliability Engineer', 'Platform Engineer', 'Cloud Engineer'],
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Linux', 'Docker'],
    related: ['software-engineer', 'data-analyst'],
    growth: 'high' },
  { slug: 'ux-designer', title: 'UX Designer', category: 'Technology', soc: '3421',
    median: 45000, lq: 34000, uq: 60000, min: 26000, max: 90000, entry: 30000, senior: 78000,
    alts: ['Product Designer', 'UI/UX Designer', 'Interaction Designer'],
    skills: ['Figma', 'User research', 'Wireframing', 'Prototyping', 'Design systems'],
    related: ['product-manager', 'software-engineer'],
    growth: 'medium' },

  // Finance
  { slug: 'financial-analyst', title: 'Financial Analyst', category: 'Finance', soc: '3534',
    median: 48000, lq: 36000, uq: 65000, min: 28000, max: 110000, entry: 32000, senior: 90000,
    alts: ['Investment Analyst', 'FP&A Analyst', 'Corporate Finance Analyst'],
    skills: ['Financial modelling', 'Excel', 'VBA', 'Valuation', 'Forecasting'],
    related: ['accountant', 'investment-banker', 'risk-manager'],
    growth: 'medium' },
  { slug: 'accountant', title: 'Accountant', category: 'Finance', soc: '2421',
    median: 42000, lq: 32000, uq: 58000, min: 25000, max: 95000, entry: 28000, senior: 78000,
    alts: ['Chartered Accountant', 'Management Accountant', 'Financial Accountant'],
    skills: ['ACCA', 'ACA', 'IFRS', 'Tax', 'Audit', 'Xero'],
    related: ['financial-analyst', 'financial-controller'],
    growth: 'medium' },
  { slug: 'investment-banker', title: 'Investment Banker', category: 'Finance', soc: '3534',
    median: 85000, lq: 60000, uq: 140000, min: 45000, max: 350000, entry: 55000, senior: 220000,
    alts: ['M&A Analyst', 'Corporate Finance Associate', 'ECM Analyst'],
    skills: ['DCF modelling', 'Pitch decks', 'Valuation', 'Deal execution', 'Client relations'],
    related: ['financial-analyst', 'risk-manager'],
    growth: 'medium' },
  { slug: 'risk-manager', title: 'Risk Manager', category: 'Finance', soc: '3534',
    median: 68000, lq: 50000, uq: 92000, min: 38000, max: 150000, entry: 42000, senior: 125000,
    alts: ['Credit Risk Manager', 'Operational Risk Manager', 'Market Risk Analyst'],
    skills: ['Basel III', 'VaR', 'Stress testing', 'SQL', 'Python'],
    related: ['financial-analyst', 'compliance-officer'],
    growth: 'medium' },
  { slug: 'financial-controller', title: 'Financial Controller', category: 'Finance', soc: '2421',
    median: 75000, lq: 58000, uq: 98000, min: 45000, max: 150000, entry: 50000, senior: 130000,
    alts: ['Group Controller', 'Head of Finance', 'Finance Director'],
    skills: ['IFRS', 'Consolidation', 'Audit', 'Team leadership', 'ERP systems'],
    related: ['accountant', 'financial-analyst'],
    growth: 'medium' },

  // Marketing
  { slug: 'marketing-manager', title: 'Marketing Manager', category: 'Marketing', soc: '1134',
    median: 48000, lq: 36000, uq: 65000, min: 28000, max: 110000, entry: 32000, senior: 90000,
    alts: ['Senior Marketing Manager', 'Head of Marketing', 'Marketing Director'],
    skills: ['Campaign planning', 'Budget management', 'Analytics', 'Team leadership'],
    related: ['seo-manager', 'content-manager', 'paid-media-manager', 'brand-manager'],
    growth: 'medium' },
  { slug: 'seo-manager', title: 'SEO Manager', category: 'Marketing', soc: '2472',
    median: 45000, lq: 34000, uq: 60000, min: 26000, max: 85000, entry: 28000, senior: 75000,
    alts: ['SEO Consultant', 'Technical SEO Lead', 'Organic Growth Manager'],
    skills: ['Ahrefs', 'Google Search Console', 'Technical SEO', 'Content strategy', 'Link building'],
    related: ['content-manager', 'paid-media-manager', 'marketing-manager'],
    growth: 'high' },
  { slug: 'content-manager', title: 'Content Manager', category: 'Marketing', soc: '2472',
    median: 38000, lq: 29000, uq: 50000, min: 24000, max: 72000, entry: 25000, senior: 62000,
    alts: ['Content Marketing Manager', 'Content Lead', 'Editorial Manager'],
    skills: ['Content strategy', 'SEO', 'Copywriting', 'CMS platforms', 'Analytics'],
    related: ['seo-manager', 'brand-manager', 'marketing-manager'],
    growth: 'medium' },
  { slug: 'paid-media-manager', title: 'Paid Media Manager', category: 'Marketing', soc: '2472',
    median: 45000, lq: 34000, uq: 58000, min: 26000, max: 85000, entry: 28000, senior: 72000,
    alts: ['PPC Manager', 'Performance Marketing Manager', 'Digital Media Buyer'],
    skills: ['Google Ads', 'Meta Ads', 'LinkedIn Ads', 'GA4', 'Attribution'],
    related: ['seo-manager', 'marketing-manager'],
    growth: 'high' },
  { slug: 'brand-manager', title: 'Brand Manager', category: 'Marketing', soc: '1134',
    median: 45000, lq: 35000, uq: 60000, min: 28000, max: 95000, entry: 32000, senior: 80000,
    alts: ['Senior Brand Manager', 'Brand Director', 'Category Manager'],
    skills: ['Brand strategy', 'Market research', 'Campaign management', 'Creative direction'],
    related: ['marketing-manager', 'content-manager'],
    growth: 'medium' },

  // Healthcare
  { slug: 'nurse', title: 'Nurse', category: 'Healthcare', soc: '2231',
    median: 35000, lq: 28500, uq: 42500, min: 25000, max: 55000, entry: 27000, senior: 50000,
    alts: ['Registered Nurse', 'Staff Nurse', 'Ward Nurse'],
    skills: ['Clinical care', 'NMC registration', 'Medication administration', 'Patient assessment'],
    related: ['physiotherapist', 'radiographer', 'pharmacist'],
    growth: 'high' },
  { slug: 'physiotherapist', title: 'Physiotherapist', category: 'Healthcare', soc: '2221',
    median: 38000, lq: 30000, uq: 48000, min: 27000, max: 62000, entry: 28000, senior: 55000,
    alts: ['Chartered Physiotherapist', 'MSK Physiotherapist', 'Physio'],
    skills: ['Musculoskeletal assessment', 'Rehabilitation', 'HCPC registration', 'Manual therapy'],
    related: ['nurse', 'radiographer'],
    growth: 'medium' },
  { slug: 'radiographer', title: 'Radiographer', category: 'Healthcare', soc: '2223',
    median: 40000, lq: 32000, uq: 50000, min: 28000, max: 65000, entry: 28500, senior: 58000,
    alts: ['Diagnostic Radiographer', 'Therapeutic Radiographer', 'MRI Radiographer'],
    skills: ['MRI', 'CT', 'X-ray', 'Patient care', 'HCPC registration'],
    related: ['nurse', 'physiotherapist'],
    growth: 'medium' },
  { slug: 'pharmacist', title: 'Pharmacist', category: 'Healthcare', soc: '2213',
    median: 48000, lq: 38000, uq: 60000, min: 32000, max: 85000, entry: 35000, senior: 72000,
    alts: ['Community Pharmacist', 'Hospital Pharmacist', 'Clinical Pharmacist'],
    skills: ['Medicines optimisation', 'GPhC registration', 'Clinical checking', 'Consultations'],
    related: ['nurse', 'gp'],
    growth: 'medium' },
  { slug: 'gp', title: 'GP', category: 'Healthcare', soc: '2211',
    median: 105000, lq: 85000, uq: 135000, min: 70000, max: 180000, entry: 75000, senior: 160000,
    alts: ['General Practitioner', 'Family Doctor', 'Primary Care Physician'],
    skills: ['GMC registration', 'MRCGP', 'Clinical diagnosis', 'Patient consultation'],
    related: ['nurse', 'pharmacist'],
    growth: 'medium' },

  // Legal
  { slug: 'solicitor', title: 'Solicitor', category: 'Legal', soc: '2412',
    median: 58000, lq: 42000, uq: 85000, min: 30000, max: 180000, entry: 35000, senior: 140000,
    alts: ['Associate Solicitor', 'Senior Solicitor', 'Legal Counsel'],
    skills: ['SRA qualification', 'Contract law', 'Legal research', 'Client advisory'],
    related: ['paralegal', 'barrister', 'compliance-officer'],
    growth: 'medium' },
  { slug: 'paralegal', title: 'Paralegal', category: 'Legal', soc: '4122',
    median: 28000, lq: 23000, uq: 35000, min: 20000, max: 48000, entry: 22000, senior: 42000,
    alts: ['Legal Assistant', 'Legal Executive', 'CILEX Paralegal'],
    skills: ['Legal research', 'Document drafting', 'Case management', 'Client liaison'],
    related: ['solicitor', 'legal-secretary'],
    growth: 'medium' },
  { slug: 'barrister', title: 'Barrister', category: 'Legal', soc: '2412',
    median: 75000, lq: 45000, uq: 135000, min: 28000, max: 400000, entry: 35000, senior: 250000,
    alts: ['Junior Barrister', 'Queens Counsel', 'QC'],
    skills: ['BSB qualification', 'Advocacy', 'Case preparation', 'Legal argument'],
    related: ['solicitor'],
    growth: 'medium' },
  { slug: 'legal-secretary', title: 'Legal Secretary', category: 'Legal', soc: '4215',
    median: 26000, lq: 22000, uq: 32000, min: 19000, max: 42000, entry: 21000, senior: 38000,
    alts: ['Legal Administrator', 'Executive Legal Assistant', 'Legal PA'],
    skills: ['Legal terminology', 'Audio typing', 'Case management systems', 'Client liaison'],
    related: ['paralegal'],
    growth: 'low' },
  { slug: 'compliance-officer', title: 'Compliance Officer', category: 'Legal', soc: '3544',
    median: 52000, lq: 38000, uq: 72000, min: 30000, max: 125000, entry: 32000, senior: 105000,
    alts: ['Compliance Manager', 'Regulatory Officer', 'Risk & Compliance Analyst'],
    skills: ['FCA regulations', 'AML', 'KYC', 'Risk assessment', 'Audit'],
    related: ['risk-manager', 'solicitor'],
    growth: 'high' },

  // Construction
  { slug: 'site-manager', title: 'Site Manager', category: 'Construction', soc: '1122',
    median: 55000, lq: 42000, uq: 72000, min: 32000, max: 110000, entry: 38000, senior: 95000,
    alts: ['Construction Manager', 'Site Agent', 'Senior Site Manager'],
    skills: ['CSCS', 'SMSTS', 'Programme management', 'Health & safety', 'Subcontractor coordination'],
    related: ['quantity-surveyor', 'project-manager', 'structural-engineer'],
    growth: 'medium' },
  { slug: 'quantity-surveyor', title: 'Quantity Surveyor', category: 'Construction', soc: '2433',
    median: 52000, lq: 40000, uq: 68000, min: 30000, max: 100000, entry: 34000, senior: 85000,
    alts: ['Senior QS', 'Commercial Manager', 'Cost Consultant'],
    skills: ['RICS', 'NEC contracts', 'JCT contracts', 'Cost planning', 'Valuation'],
    related: ['site-manager', 'project-manager'],
    growth: 'medium' },
  { slug: 'structural-engineer', title: 'Structural Engineer', category: 'Construction', soc: '2121',
    median: 48000, lq: 36000, uq: 65000, min: 28000, max: 95000, entry: 30000, senior: 82000,
    alts: ['Civil Engineer', 'Chartered Structural Engineer', 'Design Engineer'],
    skills: ['Tekla', 'Revit', 'Eurocodes', 'IStructE chartership', 'Structural analysis'],
    related: ['architect', 'site-manager'],
    growth: 'medium' },
  { slug: 'architect', title: 'Architect', category: 'Construction', soc: '2431',
    median: 48000, lq: 36000, uq: 65000, min: 28000, max: 110000, entry: 30000, senior: 90000,
    alts: ['Senior Architect', 'Associate Architect', 'Project Architect'],
    skills: ['ARB registration', 'RIBA Part 3', 'AutoCAD', 'Revit', 'Planning applications'],
    related: ['structural-engineer', 'project-manager'],
    growth: 'medium' },
  { slug: 'project-manager', title: 'Project Manager', category: 'Construction', soc: '2431',
    median: 55000, lq: 42000, uq: 75000, min: 32000, max: 120000, entry: 38000, senior: 100000,
    alts: ['Senior Project Manager', 'Programme Manager', 'PMO Manager'],
    skills: ['PRINCE2', 'APM', 'Budget management', 'Stakeholder management', 'Risk management'],
    related: ['site-manager', 'quantity-surveyor', 'product-manager'],
    growth: 'medium' },
];

// UK cities with ONS-derived multipliers (national median = 1.00)
// Multiplier reflects regional pay differential + industry mix.
const locations = [
  { slug: 'london', name: 'London', region: 'Greater London',
    pop: 9500000, mult: 1.28, col: 143, rent: 1950, unemp: 5.2,
    employers: ['HSBC', 'Barclays', 'Deloitte', 'Google UK', 'Unilever'] },
  { slug: 'manchester', name: 'Manchester', region: 'North West',
    pop: 2900000, mult: 1.02, col: 88, rent: 1050, unemp: 4.8,
    employers: ['BBC', 'Kellogg\'s', 'Co-op', 'AutoTrader', 'Bupa'] },
  { slug: 'birmingham', name: 'Birmingham', region: 'West Midlands',
    pop: 2650000, mult: 0.98, col: 82, rent: 950, unemp: 5.9,
    employers: ['HSBC UK', 'PwC', 'Jaguar Land Rover', 'Deutsche Bank', 'KPMG'] },
  { slug: 'edinburgh', name: 'Edinburgh', region: 'Scotland',
    pop: 540000, mult: 1.08, col: 92, rent: 1250, unemp: 3.8,
    employers: ['RBS', 'Standard Life Aberdeen', 'Lloyds', 'Scottish Government', 'Amazon'] },
  { slug: 'glasgow', name: 'Glasgow', region: 'Scotland',
    pop: 1680000, mult: 0.97, col: 82, rent: 925, unemp: 4.6,
    employers: ['JPMorgan', 'Morgan Stanley', 'Barclays', 'NHS Scotland', 'BBC Scotland'] },
  { slug: 'leeds', name: 'Leeds', region: 'Yorkshire',
    pop: 820000, mult: 1.00, col: 84, rent: 975, unemp: 4.4,
    employers: ['Asda', 'Sky', 'First Direct', 'NHS Digital', 'Lowell'] },
  { slug: 'bristol', name: 'Bristol', region: 'South West',
    pop: 700000, mult: 1.06, col: 94, rent: 1350, unemp: 3.9,
    employers: ['Airbus', 'Lloyds Bank', 'Hargreaves Lansdown', 'Rolls-Royce', 'BBC'] },
  { slug: 'liverpool', name: 'Liverpool', region: 'North West',
    pop: 910000, mult: 0.93, col: 80, rent: 875, unemp: 5.8,
    employers: ['Princes Food', 'Shop Direct', 'AstraZeneca', 'Jaguar Land Rover', 'Unilever'] },
  { slug: 'newcastle', name: 'Newcastle', region: 'North East',
    pop: 810000, mult: 0.92, col: 78, rent: 825, unemp: 5.1,
    employers: ['Sage', 'Newcastle Building Society', 'Barclays', 'HMRC', 'Nissan'] },
  { slug: 'sheffield', name: 'Sheffield', region: 'Yorkshire',
    pop: 585000, mult: 0.93, col: 79, rent: 825, unemp: 4.7,
    employers: ['Sheffield Forgemasters', 'HSBC', 'University of Sheffield', 'Plusnet', 'Capita'] },
  { slug: 'cardiff', name: 'Cardiff', region: 'Wales',
    pop: 480000, mult: 0.95, col: 81, rent: 925, unemp: 4.3,
    employers: ['Admiral Group', 'BBC Wales', 'Principality', 'Legal & General', 'NHS Wales'] },
  { slug: 'belfast', name: 'Belfast', region: 'Northern Ireland',
    pop: 345000, mult: 0.90, col: 76, rent: 825, unemp: 3.6,
    employers: ['Citi', 'PwC', 'Allstate', 'Liberty IT', 'BT'] },
  { slug: 'nottingham', name: 'Nottingham', region: 'East Midlands',
    pop: 730000, mult: 0.94, col: 80, rent: 875, unemp: 5.0,
    employers: ['Boots', 'Experian', 'Capital One', 'E.ON', 'Speedo'] },
  { slug: 'southampton', name: 'Southampton', region: 'South East',
    pop: 270000, mult: 1.04, col: 91, rent: 1150, unemp: 3.8,
    employers: ['Carnival UK', 'BP', 'Ordnance Survey', 'Lloyds Register', 'Southampton FC'] },
  { slug: 'reading', name: 'Reading', region: 'South East',
    pop: 230000, mult: 1.12, col: 108, rent: 1425, unemp: 2.9,
    employers: ['Microsoft', 'Oracle', 'Prudential', 'Huawei', 'PepsiCo'] },
  { slug: 'cambridge', name: 'Cambridge', region: 'East of England',
    pop: 145000, mult: 1.15, col: 115, rent: 1550, unemp: 2.6,
    employers: ['AstraZeneca', 'ARM', 'Microsoft Research', 'University of Cambridge', 'Amazon'] },
  { slug: 'oxford', name: 'Oxford', region: 'South East',
    pop: 165000, mult: 1.13, col: 118, rent: 1575, unemp: 2.8,
    employers: ['University of Oxford', 'Oxford Instruments', 'BMW Mini', 'Unipart', 'Sophos'] },
  { slug: 'milton-keynes', name: 'Milton Keynes', region: 'South East',
    pop: 290000, mult: 1.05, col: 95, rent: 1125, unemp: 3.7,
    employers: ['Santander UK', 'Mercedes-Benz', 'Argos', 'Volkswagen Financial Services', 'Network Rail'] },
  { slug: 'aberdeen', name: 'Aberdeen', region: 'Scotland',
    pop: 225000, mult: 1.04, col: 86, rent: 900, unemp: 4.2,
    employers: ['BP', 'Shell', 'TotalEnergies', 'Apache', 'Robert Gordon University'] },
  { slug: 'brighton', name: 'Brighton', region: 'South East',
    pop: 275000, mult: 1.05, col: 105, rent: 1475, unemp: 4.1,
    employers: ['American Express', 'Brandwatch', 'Legal & General', 'Gatwick Airport', 'NHS Sussex'] },
];

// Minimal FTSE 350 company seed (spec requires company template)
const companies = [
  { slug: 'hsbc', name: 'HSBC Holdings', sector: 'Banking', ftse: 'FTSE 100',
    employees: 220000, hq: 'London', avg: 68000,
    roles: [
      { role: 'Software Engineer', median: 62000, range: [42000, 92000] },
      { role: 'Financial Analyst', median: 55000, range: [38000, 78000] },
      { role: 'Risk Manager', median: 82000, range: [58000, 130000] },
      { role: 'Compliance Officer', median: 62000, range: [42000, 95000] },
    ] },
  { slug: 'barclays', name: 'Barclays', sector: 'Banking', ftse: 'FTSE 100',
    employees: 85000, hq: 'London', avg: 72000,
    roles: [
      { role: 'Software Engineer', median: 65000, range: [45000, 95000] },
      { role: 'Investment Banker', median: 95000, range: [62000, 180000] },
      { role: 'Data Analyst', median: 48000, range: [35000, 68000] },
      { role: 'Risk Manager', median: 85000, range: [60000, 135000] },
    ] },
  { slug: 'astrazeneca', name: 'AstraZeneca', sector: 'Pharmaceuticals', ftse: 'FTSE 100',
    employees: 89000, hq: 'Cambridge', avg: 62000,
    roles: [
      { role: 'Software Engineer', median: 58000, range: [40000, 85000] },
      { role: 'Data Analyst', median: 45000, range: [32000, 62000] },
      { role: 'Pharmacist', median: 55000, range: [42000, 72000] },
      { role: 'Project Manager', median: 68000, range: [48000, 95000] },
    ] },
  { slug: 'unilever', name: 'Unilever', sector: 'Consumer Goods', ftse: 'FTSE 100',
    employees: 128000, hq: 'London', avg: 58000,
    roles: [
      { role: 'Marketing Manager', median: 62000, range: [42000, 92000] },
      { role: 'Brand Manager', median: 65000, range: [45000, 98000] },
      { role: 'Financial Analyst', median: 52000, range: [38000, 75000] },
      { role: 'Data Analyst', median: 44000, range: [32000, 62000] },
    ] },
  { slug: 'bp', name: 'BP', sector: 'Energy', ftse: 'FTSE 100',
    employees: 68000, hq: 'London', avg: 72000,
    roles: [
      { role: 'Software Engineer', median: 68000, range: [45000, 98000] },
      { role: 'Project Manager', median: 78000, range: [55000, 115000] },
      { role: 'Financial Analyst', median: 58000, range: [42000, 82000] },
      { role: 'Structural Engineer', median: 62000, range: [45000, 92000] },
    ] },
];

// Write jobs
for (const j of jobs) {
  const data = {
    slug: j.slug,
    title: j.title,
    alternativeTitles: j.alts,
    category: j.category,
    sectorCode: j.soc,
    nationalMedianSalary: j.median,
    nationalLowerQuartile: j.lq,
    nationalUpperQuartile: j.uq,
    nationalMinimum: j.min,
    nationalMaximum: j.max,
    entryLevelSalary: j.entry,
    seniorLevelSalary: j.senior,
    requiredSkills: j.skills,
    relatedJobs: j.related,
    growthOutlook: j.growth,
    source: 'ONS ASHE',
    lastUpdated: TODAY,
  };
  writeFileSync(join(JOBS_DIR, `${j.slug}.json`), JSON.stringify(data, null, 2));
}

// Write locations
for (const l of locations) {
  const data = {
    slug: l.slug,
    name: l.name,
    region: l.region,
    population: l.pop,
    locationMultiplier: l.mult,
    costOfLivingIndex: l.col,
    averageRent1Bed: l.rent,
    unemploymentRate: l.unemp,
    majorEmployers: l.employers,
  };
  writeFileSync(join(LOCS_DIR, `${l.slug}.json`), JSON.stringify(data, null, 2));
}

// Write companies
for (const c of companies) {
  const data = {
    slug: c.slug,
    name: c.name,
    sector: c.sector,
    ftseIndex: c.ftse,
    employeeCount: c.employees,
    headquarters: c.hq,
    averageSalary: c.avg,
    salaryByRole: c.roles,
    lastUpdated: TODAY,
  };
  writeFileSync(join(COMP_DIR, `${c.slug}.json`), JSON.stringify(data, null, 2));
}

console.log(`Wrote ${jobs.length} jobs, ${locations.length} locations, ${companies.length} companies`);
